@catalog=http://localhost:3000
@purchasing=http://localhost:3001
@inventory=http://localhost:3002
@pricing=http://localhost:3003

###

GET {{catalog}}/products

###

GET {{purchasing}}/products

###

GET {{inventory}}/products

###

GET {{pricing}}/products

###

GET {{pricing}}/purchases

###

GET {{purchasing}}/products/1/purchases

###

POST {{purchasing}}/products/1/purchases
Content-Type: application/json; charset=utf-8

{ "quantity": 2 }

###

PUT {{inventory}}/products/2/increase-quantity
Content-Type: application/json; charset=utf-8

{ "amount": 1 }

###

POST {{catalog}}/products
Content-Type: application/json; charset=utf-8

{ "name": "Product 1" }

###

POST {{catalog}}/products
Content-Type: application/json; charset=utf-8

{ "name": "Product 2" }

###

POST {{catalog}}/products
Content-Type: application/json; charset=utf-8

{ "name": "Product 3" }
