@catalog=http://localhost:3000
@purchasing=http://localhost:3001

###

GET {{catalog}}/products

###

GET {{purchasing}}/products

###

POST {{catalog}}/products
Content-Type: application/json; charset=utf-8

{ "name": "Product 1" }

###

POST {{catalog}}/products
Content-Type: application/json; charset=utf-8

{ "name": "Product 2" }

###

POST {{catalog}}/products
Content-Type: application/json; charset=utf-8

{ "name": "Product 3" }
